### ISSUE TITLE
TileStrategy

### ISSUE THREAD

**Issue by marcomulinex** [Bayer-Group/pado#23]
What is the point of TileStrategy within TileDataset? Does not seem to obvious from reading the code to me (other than precompute which is not implemented yet). And what is one of the default strategies?

**Comment by ap--** [comment]
FastGridTiling is currently the only implementation of a TilingStrategy.

The idea is here, that implementations could trade off the amount of data needed to load to make better decisions about tiling, and that tilings can be serialized to allow random tile access on large image datasets without overhead.

https://github.com/Bayer-Group/pado/blob/635d7b8b57e527254d6302730100a6dab5a2095f/pado/images/tiles.py#L355-L435

**Comment by marcomulinex** [comment]
Works as described!
