### ISSUE TITLE
Compatibility of TileDataset with Dataloder

### ISSUE THREAD

**Issue by marcomulinex** [Bayer-Group/pado#24]
The following code

  ```
  ds = PadoDataset('../../../../pathdrive-pado-tggates/local_dataset/', 'r')
  ds = ds.filter(filter_local)

    tile_ds = TileDataset(
        ds,
        tiling_strategy=FastGridTiling(
            tile_size=(512, 512),
            target_mpp=MPP(1, 1),
            overlap=0,
            min_chunk_size=0.5,
            normalize_chunk_sizes=True,
        )
    )

    dl = DataLoader(tile_ds, batch_size=2)
    for batch in dl:
        print(batch)
        break
```

gives the following error 

`TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>
`
I assume it's because some of the metadata is None

`ImageId('acetamide', 'Kidney', '65440.svs', sit...     713         1              1     acetamide  Kidney  ftp://ftp.biosciencedbc.jp/archive/open-tggate...        1/1     Rat             Repeat  ...         345600.0   0.0      mg/kg     None       None         None            None       None   None`

Iterating directly over the TileDataset works fine though, the issue seems to come from when I feed the TileDataset to the Dataloader.

**Comment by marcomulinex** [comment]
If I pass explicitly the collate_fn defined in TileDataset

```def collate_fn(batch: list[PadoTileItem]) -> CollatedPadoTileItems:
    it = zip(PadoTileItem._fields, map(list, zip(*batch)))
    # noinspection PyArgumentList
    dct = CollatedPadoTileItems(it)  # type: ignore
    tile = dct["tile"]
    # collate tiles
    if tile:
        if isinstance(tile[0], np.ndarray):
            dct["tile"] = np.stack(tile)
        else:
            dct["tile"] = stack(tile)
    return dct
```

as follows 

`dl = DataLoader(tile_ds, batch_size=2, collate_fn=collate_fn)`

everything works. I would expect DataLoader to call the internal collate_fn automatically?

**Comment by ap--** [comment]
This is by design. Check here to see how the dataset's collate_fn method is passed to the DataLoader constructor:

https://github.com/Bayer-Group/pado/blob/635d7b8b57e527254d6302730100a6dab5a2095f/pado/itertools.py#L621-L637

We could check if since this was written, pytorch made changes that allow a dataset to provide these methods via inspection.

**Comment by marcomulinex** [comment]
Works as suggested!
