### ISSUE TITLE
Cannot create pado dataset from open tg-gates

### ISSUE THREAD

**Issue by wolny** [Bayer-Group/pado#26]
Hi there, thanks for the nice library helping with the byzantine task of accessing histopathological data 🙌 

I have downloaded the [Open TG-GATEs](https://dbarchive.biosciencedbc.jp/en/open-tggates-pathological-images/desc.html) dataset and tried to create a `pado` dataset from it, but run into issues. Here's what I've tried:

1. I've updated the serialised image provider from https://github.com/bayer-int/pathdrive-pado-tggates using:
```python
from pado.dataset import PadoDataset
from pado.images.providers import ImageProvider
from pado.images.providers import update_image_provider_urlpaths

img_provider_parquet = "./data/tggates.image.parquet"
tg_gates_directory = "..."
updated_img_provider_parquet = "./updated_tggates.image.parquet"

ip = ImageProvider.from_parquet(old_img_provider_path)
update_image_provider_urlpaths(
    tg_gates_directory,
    search_glob="**/*.svs",
    provider=ip,
    inplace=True,
    progress=True,
)
ip.to_parquet(updated_img_provider_parquet)
```

2. This worked, and then I tried to create new pado dataset:
```python
ds = PadoDataset("./my_tggates_dataset/", mode="w")
ip = ImageProvider.from_parquet(updated_img_provider_parquet)
ds.ingest_obj(ip)
print(ds[0].image)
```

which fails with:

```
Traceback (most recent call last):
    print(ds[0].image)
          ~~^^^
  File "workspace/pado/pado/dataset.py", line 274, in __getitem__
    self.images[image_id],
    ~~~~~~~~~~~^^^^^^^^^^
  File "workspace/pado/pado/images/providers.py", line 149, in __getitem__
    return self.__getitem_cached__(image_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "workspace/pado/pado/images/providers.py", line 157, in __getitem_uncached__
    return Image.from_obj(row)
           ^^^^^^^^^^^^^^^^^^^
  File "workspace/pado/pado/images/image.py", line 158, in from_obj
    md = _SerializedImage.parse_obj(obj)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/pado/lib/python3.12/site-packages/pydantic/main.py", line 1072, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/pado/lib/python3.12/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for _SerializedImage
  Input should be a valid dictionary or instance of _SerializedImage [type=model_type, input_value=urlpath                  ...tggates'), dtype: object, input_type=Series]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
```

Any ideas of how to work around this? Cheers!

**Comment by ap--** [comment]
Hey @wolny,

I wrote pado back in pydantic v1.x times, and the current version is not compatible with v2.x

```shell
python3.10 -m venv venv310
source venv310/bin/activate
pip install pado"[cli,create]" \
  git+https://github.com/bayer-science-for-a-better-life/pathdrive-pado-tggates \
  rich pydantic"<2"
```

should get you started

**Comment by sdvillal** [comment]
Ah breaking changes.

@wolny It seems that no other dependency keeps us from bumping pado to use pydantic v2 in our environments. I personally would favor adapting pado and pinning to ```pydantic >=2,<3``` to requiring ```<2```.

From pado's dependencies, at least the latest geojson-pydantic [also updated before going stable](https://github.com/developmentseed/geojson-pydantic/blob/main/CHANGELOG.md#100---2023-07-24).

It seems there might be a couple of easy routes to migrate or at least be able to work with pydantic v2 installation with minimal changes:
https://docs.pydantic.dev/latest/migration

@ap-- would you accept a PR bumping pydantic?

**Comment by ap--** [comment]
> @ap-- would you accept a PR bumping pydantic?

Of course. Feel free to change anything to make it more useful

**Comment by wolny** [comment]
Thanks for your help @ap-- and @sdvillal. I'd be happy to give `pydantic v2` migration a try.

**Comment by wolny** [comment]
I was able to adapt the code a bit (https://github.com/bayer-int/pathdrive-pado-tggates/pull/14) and successfully created `PadoDataset` from TG-GATES. Let's close this one an tackle `pydantic` migration in another issue
